# Generated by Django 4.2.2 on 2023-07-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_perfil_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='bajada',
            field=models.CharField(max_length=250, verbose_name='Bajada'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=300, unique=True, verbose_name='Título'),
        ),
    ]
